name: tempus
description: "A metronome desktop app built with Flutter, focused on simplicity and a minimal UI."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  shared_preferences: ^2.5.3
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.0.0
  media_kit_libs_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.5
  freezed: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/claves.mp3
